import type { NextPage } from "next";
import { useState } from "react";
import { AnimatePresence } from "framer-motion";
import Head from "next/head";
import Blog from "../Module/LandingPage/Blog";
import BlogSubscription from "../Module/LandingPage/BlogSubscription";
import Features from "../Module/LandingPage/Features";
import Header from "../Module/LandingPage/Header";
import Services from "../Module/LandingPage/Services";
import SocialMedia from "../Module/LandingPage/SocialMedia";
import Steps from "../Module/LandingPage/Steps";
import Testimonials from "../Module/LandingPage/Testimonials";
import Footer from "../Module/LandingPage/Footer";
import PopUpLogin from "../Module/LandingPage/PopUpLogin";

const Home: NextPage = () => {
  const [loginModalOpen, setLoginModalOpen] = useState(false);
  const OpenLoginModal = () => {
    if (loginModalOpen === false) document.body.style.overflow = "hidden";

    if (loginModalOpen === true) document.body.style.overflow = "auto";

    setLoginModalOpen((prev) => !prev);
  };

  return (
    <div style={{ scrollBehavior: "smooth" }}>
      <Head>
        <title>WorkOutly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header onClick={OpenLoginModal} />
        <Services />
        <Features />
        <Steps />
        <Testimonials />
        <Blog />
        <BlogSubscription />
        <SocialMedia />
        <Footer />
      </main>
      <AnimatePresence
        initial={false}
        exitBeforeEnter={true}
        onExitComplete={() => null}
      >
        {loginModalOpen && <PopUpLogin onClick={OpenLoginModal} />}
      </AnimatePresence>
    </div>
  );
};

export default Home;
